name: flori-custom-desktop
description: Minimalistisches Gaming- und Bastel-System mit Niri, Yazi und Ghostty
base-image: ghcr.io/ublue-os/base-main
image-version: latest
modules:
  - type: akmods
    nvidia-driver: nvidia-open
    install: []
  - type: rpm-ostree
    repos:
      - copr:yalter/niri
      - copr:scottames/ghostty
      - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
    install:
      - niri
      - yazi
      - ghostty
      - greetd
      - greetd-selinux
      - tuigreet
      - xwayland-satellite
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-gnome
      - terra-release
      - noctalia-shell
  - type: files
    files:
      - usr: /usr
      - source: system
        destination: /
  - type: script
    scripts:
      - build-sysusers-fix.sh
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam
          - com.discordapp.Discord
