name: flori-custom-desktop
description: Minimalistisches Gaming- und Bastel-System mit Niri, Yazi und Ghostty
base-image: ghcr.io/ublue-os/base-main
image-version: latest
modules:
  - type: akmods
    nvidia-driver: nvidia-open
    install:
      - v4l2loopback
  - type: rpm-ostree
    repos:
      - copr:scottames/ghostty
    install:
      - niri
      - vibepanel
      - yazi
      - ghostty
      - greetd-selinux
      - greetd-regreet
      - xorg-xwayland
      - polkit-gnome
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - com.valvesoftware.Steam
          - com.discordapp.Discord
